# Generated by Django 5.2.8 on 2025-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, help_text='City at the time of order', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_full_name',
            field=models.CharField(blank=True, help_text='Recipient full name at the time of order', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_line1',
            field=models.CharField(blank=True, help_text='Address line 1 snapshot', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_line2',
            field=models.CharField(blank=True, help_text='Address line 2 snapshot', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, help_text='Recipient phone at the time of order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_pincode',
            field=models.CharField(blank=True, help_text='Pincode at the time of order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, help_text='State at the time of order', max_length=100),
        ),
    ]
