# Generated by Django 5.2.8 on 2025-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed information about the product', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Link to product image', verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_reviews',
            field=models.IntegerField(default=0, help_text='Total count of customer reviews', verbose_name='Number of reviews'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price in INR', max_digits=10, verbose_name='Price (₹)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, help_text='Average customer rating (0–5)', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Short name shown in listings', max_length=255, verbose_name='Product title'),
        ),
    ]
